### ISSUE TITLE
IE10 says it is a pop-up

### ISSUE THREAD

**Issue by mark-hahn** [PixelsCommander/Download-File-JS#1] opened 2013-07-06 22:32 UTC
I've added download-file-js to my app and it works in chrome.  In IE10 though it says it is a popup, just like it did when using window.open.

**Comment by PixelsCommander** [comment] 2013-07-22 14:56
Hi, Mark.

Sorry for late response. Download popup is expected behaviour for IE. Is not it?

**Comment by mark-hahn** [comment] 2013-07-22 16:24
I meant that it blocks it totally because of the popup blocker.  Anyway, I gave up and made it do a normal link for IE.  Bummer.

**Comment by PixelsCommander** [comment] 2013-08-08 14:21
Seems to be fixed in recent version. Can you confirm?

**Closed as completed** 2013-09-06 14:27 UTC
